### ISSUE TITLE
confirmしない send_rt_cmd を作る

### ISSUE THREAD

**Issue by chutaro** [ut-issl/python-wings-interface#21]
## 概要
confirmしない send_rt_cmd を作る

## 詳細
`send_rt_cmd_and_confirm` は送ってからHKテレメを取得して CCP_EXEC_STS を確認しているので時間がかかる。pytestの実行時間はここがボトルネックになっている。
そこで、HKを確認しないでただ送るだけの `send_rt_cmd` を作成し、すでに実行ステータスを確認した通ることが自明なコマンドはこれに置き換えることで時間を短縮したい。

## close条件
実装したら

## 備考
実装のついでに既存のpytestで置き換えられそうなところを置き換えると better

**Comment by meltingrabbit** [comment]
置き換えていって良い気がする？

**Comment by chutaro** [comment]
あ、普通にありますね、、util.py側でラップ関数作らないとって勝手に勘違いしてました

**Comment by chutaro** [comment]
そうですね、随時置き換えてきます

**Comment by meltingrabbit** [comment]
むしろ、こっちが基本関数で、あっちがutilだからね。

**Comment by meltingrabbit** [comment]
closeしてよさそうな．
